baseURL = "https://jeffs.link/"
languageCode = "en-us"
title = "Jeff's Link"
theme = "hugo-book"

# Set content directory to Link folder
contentDir = "../Link"

# Book configuration
enableGitInfo = true
disablePathToLower = true
enableEmoji = true

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Output settings
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

# Menu settings
[menu]
  # Before site name menu (default: left)
  [[menu.before]]
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.before]]
    name = "Journal"
    url = "/Journal/"
    weight = 20
  
  [[menu.before]]
    name = "Documents"
    url = "/Documents/"
    weight = 30

  # After site name menu (default: right)
  [[menu.after]]
    name = "GitHub"
    url = "https://github.com/JeffKnowlesJr/custom-obsidian-publish"
    weight = 10

# Theme settings
[params]
  # Default Light/Dark theme
  BookTheme = "dark"
  
  # (Optional, default true) Controls if menu is displayed
  BookMenuBundle = true
  
  # (Optional, default none) Set the path to a logo for the book
  # BookLogo = 'logo.png'
  
  # Set source repository location
  BookRepo = "https://github.com/JeffKnowlesJr/custom-obsidian-publish"
  
  # Enable "Edit this page" links. Requires 'BookRepo' param
  BookEditPath = 'edit/main/content'
  
  # Configure the date format used on the pages
  # (Optional, default BookDateFormat)
  BookDateFormat = 'January 2, 2006'
  
  # (Optional, default true) Enables search function with flexsearch
  BookSearch = true
  
  # (Optional, default true) Enables table of contents
  BookToc = true
  
  # (Optional, default none) Set leaf bundle to render as side menu
  # When set, you need to create leaf bundle and check structure in README
  BookSection = 'docs'

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai" 